### ISSUE TITLE
Browser start-up: "No entries found."

### ISSUE THREAD

**Issue by coin77** [vacp2p/waku-web-chat#9]
When starting up the browsero of waku-web-chat, I get the following error:

```
C:\Users\nico\nodescripts\waku-web-chat\browser>npm start

> js-webapp@1.0.0 start C:\Users\nico\nodescripts\waku-web-chat\browser
> parcel $INIT_CWD/index.html -d ./dist

Server running at http://localhost:1234
×  No entries found.
    at Bundler.bundle (C:\Users\nico\nodescripts\waku-web-chat\browser\node_modules\parcel\src\Bundler.js:275:17)
    at async Bundler.serve (C:\Users\nico\nodescripts\waku-web-chat\browser\node_modules\parcel\src\Bundler.js:842:7)
    at async Command.bundle (C:\Users\nico\nodescripts\waku-web-chat\browser\node_modules\parcel\src\cli.js:241:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-webapp@1.0.0 start: `parcel $INIT_CWD/index.html -d ./dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-webapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nico\AppData\Roaming\npm-cache\_logs\2020-12-15T13_31_32_313Z-debug.log
```

**Comment by coin77** [comment]
$INIT_CWD was not set.
